baseurl = "https://www.valleytoprepair.com"
title = "Valley Top Repair"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# Number of words of summarized post content (default 70)
summaryLength = 70

# Do not pluralize title pages by default
pluralizelisttitles = false

[module]
  [[module.imports]]
    path = "github.com/devcows/hugo-universal-theme"

[services]
    # Enable Google Analytics by retrieving the tracking code from the environment
    [services.googleAnalytics]
        id = "$GOOGLE_ANALYTICS_API_KEY"  # Use env var

# Main menu
[menu]
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "Services"
    identifier = "menu.services"
    weight     = 2

[[menu.main]]
    name       = "Services Offered"
    url        = "/services/"
    weight     = 3
    parent     = "menu.services"    

[[menu.main]]
    name       = "Pricing"
    url        = "/pricing/"
    weight     = 4
    parent     = "menu.services"

[[menu.main]]
    name       = "Hourly Rate & Pickup/Dropoff"
    url        = "/rate-fees-pickup/"
    weight     = 5
    parent     = "menu.services"

[[menu.main]]
    name       = "Warranty"
    url        = "/warranty/"
    weight     = 6
    parent     = "menu.services"

[[menu.main]]
    name       = "About"
    identifier = "menu.about"
    weight     = 7

[[menu.main]]
    name       = "About Us"
    url        = "/about/"
    weight     = 1
    parent     = "menu.about"

[[menu.main]]
    name       = "FAQ"
    url        = "/faq/"
    weight     = 2
    parent     = "menu.about"

[[menu.main]]
    identifier = "menu.contact"
    name       = "Contact"
    url        = "/contact/"
    weight     = 8

[params]

    # Google Maps widget: Retrieve the API key from the environment
    enableGoogleMaps = true
    googleMapsApiKey = "$GOOGLE_MAPS_API_KEY"  # Use env var

    latitude = "39.598085"
    longitude = "-84.030781"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "marsala"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to 50 emails each month for free.
    #
    # Enable the contact form by entering your Formspree.io endpoint URL
    formspree_action = "$FORMSPREE_ENDPOINT"

    # Formspree form supports Google reCAPTCHA Key (type v2).
    enableRecaptchaInContactForm = true
    googleRecaptchaKey = "$GOOGLE_RECAPTCHA_KEY"  # Use env var

    about_us = "<p>At Valley Top Repair, we take pride in being your trusted local partner for repair and maintenance services. Specializing in lawn and garden equipment, small engines, and light vehicle repair, we’re here to keep your equipment, machines, and vehicles running smoothly.</p>"
    copyright = "Copyright (c) 2025, Valley Top Repair LLC; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "Valley Top Repair"

    logo = "img/vtr_logo.png"
    logo_small = "img/vtr_logo-small.png"
    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong>Valley Top Repair</strong>
        <br>3150 Clear Springs Rd
        <br>Spring Valley
        <br>Ohio, 45370
      </p>
      """
      
    customCSS = ["css/custom.css"]

[permalinks]

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'vtr/data/carousel/'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = true
    cols = 3  # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'vtr/data/features'.
    # For more information take a look at the README.

[params.see_more]
    enable = true
    icon = "far fa-file-alt"
    title = "Do you want to see more?"
    subtitle = "Check out the Services we offer."
    link_url = "/services"
    link_text = "Services"

[security]
  [security.funcs]
    getenv = ["^GOOGLE_ANALYTICS_API_KEY$", "^GOOGLE_MAPS_API_KEY$", "^GOOGLE_RECAPTCHA_KEY$", "^FORMSPREE_ENDPOINT$"]  # Restrict getenv to specific variables
